name: Attempt Solution

on:
  workflow_dispatch:
    inputs:
      day:
        description: "Which day to attempt"
        required: true
      stage:
        description: "Which stage to attempt"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache inputs
        uses: actions/cache@v4
        with:
          path: ./inputs
          key: inputs-${{ secrets.CACHE_VERSION }}
          restore-keys: |
            inputs-
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Run
        run: deno run --allow-net=adventofcode.com:443 --allow-read=./inputs --allow-write=./inputs --allow-env=SESSION day_${{ github.event.inputs.day }}/stage_${{ github.event.inputs.stage }}.ts
        env:
          SESSION: ${{ secrets.SESSION }}
